restartPolicy: Always

kind: Deployment

image:
  repository: dongjiang1989/snmp-exporter
  tag: v0.19.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}

## Security context to be added to snmp-exporter pods
securityContext: {}
  # fsGroup: 1000
  # runAsUser: 1000
  # runAsNonRoot: true

## Security context to be added to snmp-exporter containers
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true

## Additional labels to add to all resources
customLabels: {}
  # app: snmp-exporter

# config:

extraConfigmapMounts: []
  # - name: snmp-exporter-configmap
  #   mountPath: /run/secrets/snmp-exporter
  #   subPath: snmp.yaml # (optional)
  #   configMap: snmp-exporter-configmap-configmap
  #   readOnly: true
  #   defaultMode: 420

## Additional secret mounts
# Defines additional mounts with secrets. Secrets must be manually created in the namespace.
extraSecretMounts: []
  # - name: secret-files
  #   mountPath: /run/secrets/snmp-exporter
  #   secretName: snmp-exporter-secret-files
  #   readOnly: true
  #   defaultMode: 420

## For RBAC support:
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true

  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources: {}
  # limits:
  #   memory: 300Mi
  # requests:
  #   memory: 50Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

service:
  annotations: {}
  type: ClusterIP
  port: 9116
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack

## An Ingress resource can provide name-based virtual hosting and TLS
## termination among other things for CouchDB deployments which are accessed
## from outside the Kubernetes cluster.
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  hosts: []
    # - chart-example.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

podAnnotations: {}

extraArgs: []
#  --history.limit=1000

replicas: 2

configmapReload:
  ## configmap-reload container name
  ##
  name: configmap-reload

  ## configmap-reload container image
  ##
  image:
    repository: dongjiang1989/configmap-reload
    tag: v0.5.0
    pullPolicy: IfNotPresent

  ## configmap-reload resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

# Enable this if you're using https://github.com/coreos/prometheus-operator
serviceMonitor:
  enabled: true
  namespace: monitoring

  path: /snmp

  # fallback to the prometheus default unless specified
  # interval: 10s
  scrapeTimeout: 10s
  module:
    - if_mib
  # relabelings: []
  additionalMetricsRelabels: {}

  ## Defaults to what's used if you follow CoreOS [Prometheus Install Instructions](https://github.com/helm/charts/tree/master/stable/prometheus-operator#tldr)
  ## [Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheus-operator-1)
  ## [Kube Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#exporters)
  selector:
    release: metrics
  # Retain the job and instance labels of the metrics pushed to the snmp-exporter
  # [Scraping SNMP-exporter](https://github.com/prometheus/snmp_exporter#configure-the-snmp_exporter-as-a-target-to-scrape)
  honorLabels: true

  params:
    - name: localhost                 # Human readable URL that will appear in Prometheus / AlertManager
      target: 127.0.0.1               # The target that snmp will scrape
      module:                         # Module used for scraping. Overrides value set in `serviceMonitor.module`
        - if_mib
      labels: {}                      # Map of labels for ServiceMonitor. Overrides value set in `serviceMonitor.selector`
      interval: 30s                   # Scraping interval. Overrides value set in `serviceMonitor.interval`
      scrapeTimeout: 30s              # Scrape timeout. Overrides value set in `serviceMonitor.scrapeTimeout`
      relabelings: []                 # MetricRelabelConfigs to apply to samples before ingestion. Overrides value set in `serviceMonitor.relabelings`
      additionalMetricsRelabels: {}   # Map of metric labels and values to add
