apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  name: {{ include "prometheus-pingmesh-exporter.fullname" . }}
  namespace: {{ template "prometheus-pingmesh-exporter.namespace" . }}
  labels:
    {{- include "prometheus-pingmesh-exporter.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
<<<<<<< HEAD
<<<<<<< HEAD
{{- if ge (.Capabilities.KubeVersion.Minor | int) 20 }}
=======
{{- if ge (.Capabilities.KubeVersion.Minor|int) 20 }}
>>>>>>> b33dcce (dongjiang, add dualStack)
=======
{{- if ge (.Capabilities.KubeVersion.Minor | int) 20 }}
>>>>>>> 327df78 (update metrics/charts/prometheus-pingmesh-exporter/templates/service.yaml)
  ipFamilies:
{{ toYaml .Values.service.ipFamilies | indent 2 }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    {{- include "prometheus-pingmesh-exporter.selectorLabels" . | nindent 4 }}
