{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loggie-config-{{ template "loggie.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: loggie
    instance: {{ template "loggie.name" . }}
spec:
  endpoints:
  - port: monitor
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    honorLabels: true
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: loggie
      instance: {{ template "loggie.name" . }}
{{- end }}
