# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: master
chart-dirs:
  - .
  - tracing
  - logging
chart-repos:
  - kubeservice-stack=https://kubeservice-stack.github.io/kubservice-charts
  - jetstack=https://charts.jetstack.io
  - grafana=https://grafana.github.io/helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - elastic=https://helm.elastic.co
  - bitnami=https://charts.bitnami.com/bitnami
  - hashicorp=https://helm.releases.hashicorp.com
  - minio=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
validate-maintainers: false
excluded-charts:
  # If not running on GCE, will error: "Failed to get GCE config"
additional-commands:
  # - helm unittest --helm3 --strict --file unittests/*.yaml --file 'unittests/**/*.yaml' {{ .Path }}
