kind: Service
apiVersion: v1
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "prometheus-snmp-exporter.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
{{- if ge (.Capabilities.KubeVersion.Minor|int) 20 }}
  ipFamilies:
{{ toYaml .Values.service.ipFamilies | indent 2 }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    {{- include "prometheus-snmp-exporter.selectorLabels" . | indent 4 }}
